import { PacketType } from 'node-insim/packets';
import type { InSim } from 'node-insim/protocols';

import { onAdminCommandReport } from './onAdminCommandReport';
import { onAutocrossInfo } from './onAutocrossInfo';
import { onAutocrossMultipleObjects } from './onAutocrossMultipleObjects';
import { onAutocrossObject } from './onAutocrossObject';
import { onButtonClick } from './onButtonClick';
import { onButtonType } from './onButtonType';
import { onCameraChange } from './onCameraChange';
import { onCamPosPack } from './onCamPosPack';
import { onCarContact } from './onCarContact';
import { onCarReset } from './onCarReset';
import { onConnectionLeave } from './onConnectionLeave';
import { onConnectionPlayerRename } from './onConnectionPlayerRename';
import { onFinish } from './onFinish';
import { onFlag } from './onFlag';
import { onHlvc } from './onHlvc';
import { onInSimInfo } from './onInSimInfo';
import { onLapTime } from './onLapTime';
import { onMessageOut } from './onMessageOut';
import { onMultiCarInfo } from './onMultiCarInfo';
import { onMultiplayer } from './onMultiplayer';
import { onNewConnection } from './onNewConnection';
import { onNewConnectionInfo } from './onNewConnectionInfo';
import { onNewPlayer } from './onNewPlayer';
import { onNodeLap } from './onNodeLap';
import { onObjectHit } from './onObjectHit';
import { onPenalty } from './onPenalty';
import { onPitLane } from './onPitLane';
import { onPitStop } from './onPitStop';
import { onPitStopFinished } from './onPitStopFinished';
import { onPlayerFlagsChanged } from './onPlayerFlagsChanged';
import { onPlayerLeave } from './onPlayerLeave';
import { onPlayerPit } from './onPlayerPit';
import { onReorder } from './onReorder';
import { onReplayInfo } from './onReplayInfo';
import { onResult } from './onResult';
import { onSendScreenshot } from './onSendScreenshot';
import { onSmall } from './onSmall';
import { onSplitTime } from './onSplitTime';
import { onState } from './onState';
import { onTakeOverCar } from './onTakeOverCar';
import { onTiny } from './onTiny';
import { onUserControlObject } from './onUserControlObject';
import { onVersion } from './onVersion';
import { onVoteNotify } from './onVoteNotify';

export function logPackets(inSim: InSim) {
  inSim.on(PacketType.ISP_VER, onVersion);
  inSim.on(PacketType.ISP_TINY, onTiny);
  inSim.on(PacketType.ISP_SMALL, onSmall);
  inSim.on(PacketType.ISP_CPP, onCamPosPack);
  inSim.on(PacketType.ISP_ISM, onMultiplayer);
  inSim.on(PacketType.ISP_MSO, onMessageOut);
  inSim.on(PacketType.ISP_III, onInSimInfo);
  inSim.on(PacketType.ISP_VTN, onVoteNotify);
  inSim.on(PacketType.ISP_STA, onState);
  inSim.on(PacketType.ISP_NCN, onNewConnection);
  inSim.on(PacketType.ISP_CNL, onConnectionLeave);
  inSim.on(PacketType.ISP_CPR, onConnectionPlayerRename);
  inSim.on(PacketType.ISP_NPL, onNewPlayer);
  inSim.on(PacketType.ISP_PLP, onPlayerPit);
  inSim.on(PacketType.ISP_PLL, onPlayerLeave);
  inSim.on(PacketType.ISP_LAP, onLapTime);
  inSim.on(PacketType.ISP_SPX, onSplitTime);
  inSim.on(PacketType.ISP_PIT, onPitStop);
  inSim.on(PacketType.ISP_PSF, onPitStopFinished);
  inSim.on(PacketType.ISP_PLA, onPitLane);
  inSim.on(PacketType.ISP_CCH, onCameraChange);
  inSim.on(PacketType.ISP_PEN, onPenalty);
  inSim.on(PacketType.ISP_TOC, onTakeOverCar);
  inSim.on(PacketType.ISP_FLG, onFlag);
  inSim.on(PacketType.ISP_PFL, onPlayerFlagsChanged);
  inSim.on(PacketType.ISP_FIN, onFinish);
  inSim.on(PacketType.ISP_RES, onResult);
  inSim.on(PacketType.ISP_REO, onReorder);
  inSim.on(PacketType.ISP_NLP, onNodeLap);
  inSim.on(PacketType.ISP_MCI, onMultiCarInfo);
  inSim.on(PacketType.ISP_CRS, onCarReset);
  inSim.on(PacketType.ISP_AXI, onAutocrossInfo);
  inSim.on(PacketType.ISP_AXO, onAutocrossObject);
  inSim.on(PacketType.ISP_BTC, onButtonClick);
  inSim.on(PacketType.ISP_BTT, onButtonType);
  inSim.on(PacketType.ISP_RIP, onReplayInfo);
  inSim.on(PacketType.ISP_SSH, onSendScreenshot);
  inSim.on(PacketType.ISP_CON, onCarContact);
  inSim.on(PacketType.ISP_OBH, onObjectHit);
  inSim.on(PacketType.ISP_HLV, onHlvc);
  inSim.on(PacketType.ISP_AXM, onAutocrossMultipleObjects);
  inSim.on(PacketType.ISP_ACR, onAdminCommandReport);
  inSim.on(PacketType.ISP_NCI, onNewConnectionInfo);
  inSim.on(PacketType.ISP_UCO, onUserControlObject);
}
