import { PacketType } from 'node-insim/packets';
import type { InSim } from 'node-insim/protocols';

import { onButtonClick } from './onButtonClick';
import { onButtonType } from './onButtonType';
import { onCameraChange } from './onCameraChange';
import { onCamPosPack } from './onCamPosPack';
import { onCarReset } from './onCarReset';
import { onConnectionLeave } from './onConnectionLeave';
import { onConnectionPlayerRename } from './onConnectionPlayerRename';
import { onFlag } from './onFlag';
import { onInSimInfo } from './onInSimInfo';
import { onLapTime } from './onLapTime';
import { onMessageOut } from './onMessageOut';
import { onMultiplayer } from './onMultiplayer';
import { onNewConnection } from './onNewConnection';
import { onNewPlayer } from './onNewPlayer';
import { onPenalty } from './onPenalty';
import { onPitLane } from './onPitLane';
import { onPitStop } from './onPitStop';
import { onPitStopFinished } from './onPitStopFinished';
import { onPlayerFlagsChanged } from './onPlayerFlagsChanged';
import { onPlayerLeave } from './onPlayerLeave';
import { onPlayerPit } from './onPlayerPit';
import { onSmall } from './onSmall';
import { onSplitTime } from './onSplitTime';
import { onState } from './onState';
import { onTakeOverCar } from './onTakeOverCar';
import { onTiny } from './onTiny';
import { onVersion } from './onVersion';
import { onVoteNotify } from './onVoteNotify';

export function logPackets(inSim: InSim) {
  inSim.on(PacketType.ISP_VER, onVersion);
  inSim.on(PacketType.ISP_TINY, onTiny);
  inSim.on(PacketType.ISP_SMALL, onSmall);
  inSim.on(PacketType.ISP_CPP, onCamPosPack);
  inSim.on(PacketType.ISP_ISM, onMultiplayer);
  inSim.on(PacketType.ISP_MSO, onMessageOut);
  inSim.on(PacketType.ISP_III, onInSimInfo);
  inSim.on(PacketType.ISP_VTN, onVoteNotify);
  inSim.on(PacketType.ISP_STA, onState);
  inSim.on(PacketType.ISP_NCN, onNewConnection);
  inSim.on(PacketType.ISP_CNL, onConnectionLeave);
  inSim.on(PacketType.ISP_CPR, onConnectionPlayerRename);
  inSim.on(PacketType.ISP_NPL, onNewPlayer);
  inSim.on(PacketType.ISP_PLP, onPlayerPit);
  inSim.on(PacketType.ISP_PLL, onPlayerLeave);
  inSim.on(PacketType.ISP_LAP, onLapTime);
  inSim.on(PacketType.ISP_SPX, onSplitTime);
  inSim.on(PacketType.ISP_PIT, onPitStop);
  inSim.on(PacketType.ISP_PSF, onPitStopFinished);
  inSim.on(PacketType.ISP_PLA, onPitLane);
  inSim.on(PacketType.ISP_CCH, onCameraChange);
  inSim.on(PacketType.ISP_PEN, onPenalty);
  inSim.on(PacketType.ISP_TOC, onTakeOverCar);
  inSim.on(PacketType.ISP_FLG, onFlag);
  inSim.on(PacketType.ISP_PFL, onPlayerFlagsChanged);
  inSim.on(PacketType.ISP_CRS, onCarReset);
  inSim.on(PacketType.ISP_BTC, onButtonClick);
  inSim.on(PacketType.ISP_BTT, onButtonType);
}
